# Generated by Django 3.2.9 on 2022-01-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='html_font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_value', models.CharField(default='fn', max_length=50)),
                ('font_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='html_shadows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shadow_value', models.CharField(default='sh', max_length=50)),
                ('shadow_name', models.CharField(max_length=50)),
            ],
        ),
    ]
