# Generated by Django 3.2.9 on 2022-01-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_html_font_html_shadows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html_font',
            name='font_value',
            field=models.CharField(default='f', max_length=50),
        ),
    ]
