# Generated by Django 3.2.9 on 2022-01-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_html_font_font_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html_color',
            name='color_value',
            field=models.CharField(default='fnc', max_length=50),
        ),
    ]
