# Generated by Django 3.2.9 on 2022-01-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_html_font_font_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html_font',
            name='font_value',
            field=models.CharField(blank=True, default='f', max_length=50),
        ),
    ]
