# Generated by Django 3.2.9 on 2022-01-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_html_font_font_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html_font',
            name='font_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
